name: Tweet bot

on:
  schedule:
    - cron: '30 17 * * 0'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install tweepy
      - name: Run bot
        run: python bot.py
        env:
          API_KEY: ${{ NoCNgnfgYXHZsg8IkkQ7VLLuY }}
          API_SECRET: ${{ HVtcHFI2XbjRVWDbZEdyzU1svofvSbV494gvLuwelhsoKJX4rG }}
          ACCESS_TOKEN: ${{ 2045960105196244992-H1bDhDmNxcoXdveFTJQMcp4ODN6W4t }}
          ACCESS_SECRET: ${{ O7oGmHXil0HvzdFdn6aKk6yw99LsmCnV4tNUlZwLVYnwg }}
